### ISSUE TITLE
[FEATURE] Add tasks from my task list

### ISSUE THREAD

**Issue by colmdoyle** [slackapi/tasks-app#15]
### Description

**As a**
User

**I want to**
create tasks from the same interface as my list of tasks

**So that I can**
Add tasks that are missing when I review my list

### Languages 

This feature is now implemented in:
- [ ] Python
- [x] Node.js
- [ ] Java

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.
