### ISSUE TITLE
[FEATURE] Prioritize/Reorder tasks on task list

### ISSUE THREAD

**Issue by illisan** [slackapi/tasks-app#31]
### Description

**As a**
User

**I want to**
Be able to reorder my tasks on my task list.

**So that I can**
Prioritize tasks that are due on the same day.
### Languages 

This feature is now implemented in:
- [ ] Python
- [ ] Node.js
- [ ] Java

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by illisan** [comment]
Another option to accomplish something similar would be to add the ability to assign a priority level to a specific task when creating it.
